### ISSUE TITLE
카드 컴포넌트 개발

### ISSUE THREAD

**Issue by again7536** [TeamNoguzi/LetsKlay#1]
## 개발 사항
- [ ] 카드 컴포넌트(Base) 개발
<img src="https://user-images.githubusercontent.com/45936642/155443940-7bd7e44a-f75b-46bc-9c4e-fc1c8822b262.png" width="200"/>

- [ ] 카드 컴포넌트(Small) 개발
<img src="https://user-images.githubusercontent.com/45936642/155444292-22fa92d0-d7d4-4c09-8faf-349c98f3baf3.png" width="200"/>

## 참고 사항
* 스토리북 코드도 작성 요망

**Comment by baldwinIV** [comment]
저를 어싸인 해주셨으니.. 스토리북의 primary, secondary 적용해서 개발해 보겠읍니다.
