### ISSUE TITLE
Editor 추가

### ISSUE THREAD

**Issue by again7536** [TeamNoguzi/LetsKlay#23]
## 개발 사항
![image](https://user-images.githubusercontent.com/45936642/156870861-ca336360-57d0-4344-9ea7-01e3bd193031.png)
- [ ] HTML 에디터 외부 모듈 사용하여 프로젝트 설명 기능 구현
    - TinyMCE, CKEditor5 등 있음
- [ ] HTML Sanitizer 사용 필수 (XSS 방지)
    - sanitize-html 모듈
## 참고 사항
- 타입스크립트 리액트 호환 여부 체크 필요

**Comment by baldwinIV** [comment]
확실히 해내겠습니다 선생님
