### ISSUE TITLE
klayton과 연결할 로직 부분 제외 API 작성

### ISSUE THREAD

**Issue by again7536** [TeamNoguzi/LetsKlay#62]
## 개발 사항
- [ ] 스마트 컨트랙트와 백엔드 연결부 로직 작성
- [ ] txId에 컨트랙트가 실행된 주소를 넣어서 참조

**Comment by baldwinIV** [comment]
충격정보 : 클레이튼의 정확한 영어 철자는 klaytn이다.. (톤..)
