### ISSUE TITLE
카드 캐러셀 개발

### ISSUE THREAD

**Issue by again7536** [TeamNoguzi/LetsKlay#7]
## 개발 내용
- [x] 카드 캐러셀 개발
<img src="https://user-images.githubusercontent.com/45936642/155657316-fa5c50e5-4c67-4b42-9cb8-fb16ac95deb4.png"/>

- 좌우로 넘길 수 있도록 해야함

## 참고 사항
#1 완료 후 진행

**Comment by baldwinIV** [comment]
https://www.npmjs.com/package/react-multi-carousel
사용 고려 중

**Comment by again7536** [comment]
이번주 주말에 올려주시길 바랍니다~

#31 참고해서 컴포넌트 로드할때 오류 없도록 부탁
